// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1pdbWM26hxgs2oFg_7kz2LXT9IAXPNBI',
    appId: '1:419658597459:web:755cc9ad6fb13e9e07f2a6',
    messagingSenderId: '419658597459',
    projectId: 'trial1-986b7',
    authDomain: 'trial1-986b7.firebaseapp.com',
    storageBucket: 'trial1-986b7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5x7qsP6u_RqSSakvbCK2GkkwepK64Xk4',
    appId: '1:419658597459:android:a05e85437608b68f07f2a6',
    messagingSenderId: '419658597459',
    projectId: 'trial1-986b7',
    storageBucket: 'trial1-986b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdTm5dfz-B6QTI-1wGP11FNRBzk_Vnz_Q',
    appId: '1:419658597459:ios:a5e74e61b078bb3e07f2a6',
    messagingSenderId: '419658597459',
    projectId: 'trial1-986b7',
    storageBucket: 'trial1-986b7.appspot.com',
    iosBundleId: 'com.example.a2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdTm5dfz-B6QTI-1wGP11FNRBzk_Vnz_Q',
    appId: '1:419658597459:ios:a5e74e61b078bb3e07f2a6',
    messagingSenderId: '419658597459',
    projectId: 'trial1-986b7',
    storageBucket: 'trial1-986b7.appspot.com',
    iosBundleId: 'com.example.a2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1pdbWM26hxgs2oFg_7kz2LXT9IAXPNBI',
    appId: '1:419658597459:web:d3b9cf890bd17ce607f2a6',
    messagingSenderId: '419658597459',
    projectId: 'trial1-986b7',
    authDomain: 'trial1-986b7.firebaseapp.com',
    storageBucket: 'trial1-986b7.appspot.com',
  );
}
